config/routes.rb
Rails.application.routes.draw do

    root 'posts#index'

    devise_for :users, controllers: { registrations: :registrations }

    resources :posts

    post 'posts/:id/comment/' => 'comments#create', as: :new_posts_comment
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base

    validates :content, presence: true

    belongs_to :post
    belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
    validates :title, presence: true
    validates :content, presence: true

    validates :published_date, presence: true

    belongs_to :user
    has_many :comments

    validates :picture, presence: true
    mount_uploader :picture, PostPictureUploader
end

app/models/user.rb
class User < ActiveRecord::Base
    extend Devise::Models

    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

    validates :firstname, presence: true
    validates :lastname, presence: true

    has_many :posts

    def fullname
        firstname + " " + lastname
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

    def create
        @comment = Comment.new(comment_params)
        @comment.user = current_user
        @comment.post_id = params[:id]

        @post = Post.find(params[:id])

        if @comment.save
            redirect_to @post
        else
            render 'new'
        end
    end

    private
    def comment_params
        params.require(:comment).permit(:content)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @posts = Post.all
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, :except => [:show, :index]

    def index
        @posts = Post.all
    end
    def create
        @post = Post.new(post_params)
        @post.user = current_user

        if @post.save
            redirect_to @post
        else
            render 'new'
        end
    end
    def new
        @post = Post.new
    end
    def edit
        @post = Post.find(params[:id])
    end
    def show
        @post = Post.find(params[:id])
        @comment = Comment.new
    end
    def update
        @post = Post.find(params[:id])

        if @post.update(post_params)
            redirect_to @post
        else
            render 'edit'
        end
    end
    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path
    end
    private
    def post_params
        params.require(:post).permit(:title, :content, :picture, :published_date)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    def sign_up_params
        params.required(:user).permit(:email, :password, :password_confirmation, :firstname, :lastname)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>RubyBlog</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="#">RubyBlog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <%= link_to '<i class="fa fa-home" aria-hidden="true"></i> Home'.html_safe, root_path, :class => "nav-link" %>
                </li>
                <% if user_signed_in? %>
                <li class="nav-item">
                    <%= link_to '<i class="fa fa-pencil" aria-hidden="true"></i> New Post'.html_safe, new_post_path, :class => "nav-link" %>
                </li>
                <% end %>
            </ul>

            <ul class="navbar-nav navbar-right">
                <% if user_signed_in? %>
                <li class="nav-item">
                    <%= link_to '<i class="fa fa-user" aria-hidden="true"></i> Profil'.html_safe, edit_user_registration_path, :class => "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to '<i class="fa fa-sign-out" aria-hidden="true"></i> Logout'.html_safe, destroy_user_session_path, :method => :delete, :class => "nav-link" %>
                </li>
                <% else %>
                <li class="nav-item">
                    <%= link_to 'Login', new_user_session_path, :class => "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to 'Register', new_user_registration_path, :class => "nav-link" %>
                </li>
                <% end %>
            </ul>
        </div>
    </nav>

    <div class="container">
        <%= yield %>
    </div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |form| %>
<div class="form-group col-9">
    <%= form.label :title %><br>
    <%= form.text_field :title, :class => "form-control" %>
</div>

<div class="form-group col-9">
    <%= form.label :content %><br>
    <%= form.text_area :content, :class => "form-control" %>
</div>

<div class="form-group col-3">
    <%= form.label :picture %><br>
    <%= form.file_field :picture, :class => "form-control" %>
</div>

<div class="form-group col-3">
    <%= form.label :published_date %><br>
    <%= form.date_field :published_date, :class => "form-control" %>
</div>

<% if @post.errors.any? %>
<ul>
    <% @post.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
</ul>
<% end %>

<div class="form-group col-6">
    <%= form.submit :class => "btn bg-dark text-white" %>
</div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= render partial: "form" %>

<div class="form-group col-6">
    <%= link_to 'Back', post_path(@post), :class => "btn btn-primary" %>
</div>

app/views/posts/index.html.erb
<div class="row">
    <% @posts.each do |post| %>
    <div class="col-4 post-preview">
        <h1><%= link_to post.title, post_path(post) %></h1>
        <p>by <%= post.user.fullname %></p>

        <p><%= post.content[0..40] %>...</p>

        <%= image_tag post.picture.small.url %>
    </div>
    <% end %>
</div>

app/views/posts/new.html.erb
<div class="offset-2">
    <div class="col-12">
        <h1>New post</h1>
    </div>

    <%= render partial: "form" %>

    <div class="col-6">
        <%= link_to 'Back', posts_path, :class => "btn btn-primary" %>
    </div>
</div>

app/views/posts/show.html.erb
<div class="col-12">
    <h1><%= @post.title %></h1>

    <p><%= @post.content %></p>

    <p>Published date : <%= @post.published_date %></p>

    <%= image_tag @post.picture.url %>

    <div class="post-controls">
        <% if current_user == @post.user %>
        <%= link_to "Edit", edit_post_path(@post), :class => "btn btn-primary" %>
        <%= link_to 'Delete', post_path(@post), :class => "btn btn-danger",
        method: :delete,
        data: { confirm: 'Are-you sure ?' } %>
        <% end %>
    </div>

    <div class="comment-list">
        <% @post.comments.each do |comment| %>
        <div>
            by <span class="comment-author"><%= comment.user.fullname %></span>
            <p><%= comment.content %></p>
        </div>
        <% end %>
    </div>

    <% if current_user %>
    <%= form_for @comment, :url => new_posts_comment_path do |form| %>
    <div class="form-group">
        <%= form.label :content, 'Comment' %>
        <%= form.text_area :content, :class => "form-control" %>
    </div>

    <div class="form-group">
        <%= form.submit :class => "btn bg-dark text-white" %>
    </div>
    <% end %>
    <% end %>
</div>